FROM nginx:1.15-alpine

EXPOSE 80
EXPOSE 443

# NEW LINES BELOW (https://github.com/gitphill/openssl-alpine)
# install openssl
# RUN apk add --update openssl && \
#    rm -rf /var/cache/apk/*


COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

COPY certs/* /etc/nginx/conf.d/certs/

RUN mkdir /etc/nginx/logs

CMD ["nginx", "-g", "daemon off;"]
