FROM nginx:1.15-alpine
#COPY index.html /usr/share/nginx/html/index.html
#COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY certs/* /etc/nginx/conf.d/certs/

EXPOSE 80
EXPOSE 443

# NEW LINES BELOW (https://github.com/gitphill/openssl-alpine)


# install openssl
#RUN apk add --update openssl && \
#    rm -rf /var/cache/apk/*

#COPY *.ext /
#COPY docker-entrypoint.sh /

#VOLUME ["$CERT_DIR"]
#ENTRYPOINT ["/docker-entrypoint.sh"]