version: '3'

networks:
  container-net:
    driver: bridge

services:

  port-listener-app:
    image: longshin/node-port-listener:cluster
    container_name: port-listener
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped  
    ports:
      - 3000:3000
    networks: 
      - container-net