version: '3'

services:

  nginx-proxy:
    build:
      context: ./nginx-proxy/
      dockerfile: Dockerfile-nginx
    image: nginx-proxy:1
    container_name: nginx-proxy
    hostname: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
        
  port-listener:
    build:
      context: ./port-listener/
      dockerfile: Dockerfile-node    
    image: port-listener:latest
    hostname: port-listener
    container_name: port-listener
    restart: unless-stopped  
    ports:
      - 3000:3000
    depends_on:
      - nginx-proxy
