FROM node:8.11.4-alpine

# Create app directory
# WORKDIR /usr/src/app

# Install app dependencies by bundling app source
COPY * ./

RUN npm install


# Command to run your app using CMD which defines the runtime. Here we will use the basic npm start which will run app.js and start the app
CMD ["npm", "start"]